# Generated by Django 5.0.1 on 2024-02-01 18:16

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_alter_status_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="file_name",
        ),
        migrations.AddField(
            model_name="photo",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=website.models.file_location
            ),
        ),
    ]
